version: "2"

linters:
  settings:
    errcheck:
      exclude-functions:
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
        - os.RemoveAll
    staticcheck:
      checks:
        - "all"
        - "-QF*"
        - "-ST*"

  exclusions:
    rules:
      - linters: [errcheck]
        source: "defer "
      - linters: [errcheck]
        path: "_test\\.go"
        source: "\\.Close\\(\\)"
